// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WalkthroughSample.iOS
{
	public partial class CustomViewController : UIViewController
	{
		public CustomViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
