#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("WalkthroughSample.Droid.Resource", IsApplication=true)]

namespace WalkthroughSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Walker.Resource.String.library_name = global::WalkthroughSample.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cloud = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int iphone = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int left_arrow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int right_arrow = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int c1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int c2 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int c3 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int c4 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int c5 = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int img = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int myButton = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int title = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int walker = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FirstFragment = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SecondFragment = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ThirdFragment = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
